public class Hello {
    public static void main(String[]args){
        System.out.println("Hello world"); // output: Hello world
    }
}

// void is return type...
// public is access modifier...
// static: the method belongs to the class itself, not an instance(object)....
// main: method name...
// String[] args : parameter , an array of string...